version: "3"

services:
  #Php-Apache
  webserver:
    image: ${VERSION_PHP}:${TAG}
    container_name: '${NOMBRE_PROYECTO}-${VERSION_PHP}'
    restart: 'always'
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    links:
      - database
    volumes:
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${APACHE_LOG_DIR}:/var/log/apache2
    environment:
      APACHE_DOCUMENT_ROOT: ${APACHE_DOCUMENT_ROOT}
      PMA_PORT: ${PMA_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  #MySQL
  database:
    image: ${VERSION_MYSQL}:${TAG}
    container_name: '${NOMBRE_PROYECTO}-${VERSION_MYSQL}'
    restart: 'always'
    ports:
      - "127.0.0.1:${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_INITDB_DIR}:/docker-entrypoint-initdb.d
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  #PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: '${NOMBRE_PROYECTO}-phpmyadmin'
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    ports:
      - '${PMA_PORT}:80'
    volumes:
      - /sessions
      - ${PHP_INI}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

  #Redis
  redis:
    image: redis:latest
    container_name: '${NOMBRE_PROYECTO}-redis'
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
